name: Ubuntu CI from source
run-name: Testing ${{ inputs.packages-to-test }} | vcs ${{ inputs.vcs-repo-file-base }} ${{ inputs.vcs-repo-file }}

on:
  workflow_dispatch:
    inputs:
      packages-to-test:
        description: Names of packages to test (e.g. 'gz-math sdformat').
        required: true
        type: string
        default: sdformat
      vcs-repo-file-base:
        description: Choose whether vcs-repo-file represents a relative path in the github workspace or a URL.
        required: true
        default: relative
        type: choice
        options:
          - relative
          - url
      vcs-repo-file:
        description: Relative path or URL to vcs repo file to import into colcon workspace
        required: true
        type: string
        default: ".github/ci/packages_up_to_sdformat.yaml"

jobs:
  noble-ci:
    runs-on: ubuntu-latest
    name: Ubuntu Noble CI (from source)
    container:
      image: rostooling/setup-ros-docker:ubuntu-noble-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Compile and test
        uses: ros-tooling/action-ros-ci@v0.4
        with:
          package-name: ${{ inputs.packages-to-test }}
          target-ros2-distro: kilted
          vcs-repo-file-url: >
            ${{ case(
              inputs.vcs-repo-file-base == 'relative', format('{0}/{1}', github.workspace, inputs.vcs-repo-file),
              inputs.vcs-repo-file
            ) }}
          colcon-defaults: |
            {
              "build": {
                "merge-install": true
              },
              "test": {
                "merge-install": true
              }
            }
